application: whotookmybook
version: 1
runtime: python
api_version: 1
default_expiration: "1d"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /s
  static_dir: s
  login: required
  
- url: /jslib
  static_dir: jslib

- url: /suggest
  static_dir: suggest

- url: /cc
  script: cc.py
  login: admin
  
- url: /test.*
  script: gaeunit.py

- url: /feed/whats_new
  script: mybooks.py

- url: /.*
  script: mybooks.py
  login: required
