application: whotookmybook
version: groups
runtime: python
api_version: 1
default_expiration: "1d"

handlers:
- url: /thanks
  static_files: thanks.html
  upload: thanks.html
  expiration: "30d"
   
- url: /s
  static_dir: s
  login: required
  expiration: "30d"

- url: /suggest
  static_dir: suggest
  expiration: "120d"

- url: /hush/(.*)
  script: /hush/\1.py
  login: admin

- url: /feed/whats_new
  script: mybooks.py

- url: /cron/keepalive
  script: mybooks.py

- url: /indexbook
  script: mybooks.py

- url: /purgeInactive
  script: mybooks.py

- url: /.*
  script: mybooks.py
  login: required